//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QPMLinksoftwareNew.QPMStore {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Config1Binding", Namespace="urn:RAWsd/Config1")]
    public partial class RA2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback addPsPropValOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPoiProValOperationCompleted;
        
        private System.Threading.SendOrPostCallback modifyPoiProValOperationCompleted;
        
        private System.Threading.SendOrPostCallback modifyPsPropValOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateTextVarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RA2() {
            this.Url = global::QPMLinksoftwareNew.Properties.Settings.Default.QPMLinksoftwareNew_QPMStore_RA2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event addPsPropValCompletedEventHandler addPsPropValCompleted;
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event addPoiProValCompletedEventHandler addPoiProValCompleted;
        
        /// <remarks/>
        public event modifyPoiProValCompletedEventHandler modifyPoiProValCompleted;
        
        /// <remarks/>
        public event modifyPsPropValCompletedEventHandler modifyPsPropValCompleted;
        
        /// <remarks/>
        public event updateTextVarCompletedEventHandler updateTextVarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:RAVi", ResponseNamespace="urn:RAVi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response", IsNullable=true)]
        public string addPsPropVal([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="urn:pl.com.bcc.ws.classes")] PsPropValWrapper[] data) {
            object[] results = this.Invoke("addPsPropVal", new object[] {
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addPsPropValAsync(PsPropValWrapper[] data) {
            this.addPsPropValAsync(data, null);
        }
        
        /// <remarks/>
        public void addPsPropValAsync(PsPropValWrapper[] data, object userState) {
            if ((this.addPsPropValOperationCompleted == null)) {
                this.addPsPropValOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPsPropValOperationCompleted);
            }
            this.InvokeAsync("addPsPropVal", new object[] {
                        data}, this.addPsPropValOperationCompleted, userState);
        }
        
        private void OnaddPsPropValOperationCompleted(object arg) {
            if ((this.addPsPropValCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPsPropValCompleted(this, new addPsPropValCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:RAVi", ResponseNamespace="urn:RAVi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response")]
        public bool delete(int mandant, int processId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string from, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string to) {
            object[] results = this.Invoke("delete", new object[] {
                        mandant,
                        processId,
                        from,
                        to});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAsync(int mandant, int processId, string from, string to) {
            this.deleteAsync(mandant, processId, from, to, null);
        }
        
        /// <remarks/>
        public void deleteAsync(int mandant, int processId, string from, string to, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        mandant,
                        processId,
                        from,
                        to}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:RAVi", ResponseNamespace="urn:RAVi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response", IsNullable=true)]
        public string addPoiProVal([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="urn:pl.com.bcc.ws.classes")] PoiProValWrapper[] data) {
            object[] results = this.Invoke("addPoiProVal", new object[] {
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addPoiProValAsync(PoiProValWrapper[] data) {
            this.addPoiProValAsync(data, null);
        }
        
        /// <remarks/>
        public void addPoiProValAsync(PoiProValWrapper[] data, object userState) {
            if ((this.addPoiProValOperationCompleted == null)) {
                this.addPoiProValOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPoiProValOperationCompleted);
            }
            this.InvokeAsync("addPoiProVal", new object[] {
                        data}, this.addPoiProValOperationCompleted, userState);
        }
        
        private void OnaddPoiProValOperationCompleted(object arg) {
            if ((this.addPoiProValCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPoiProValCompleted(this, new addPoiProValCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:RAVi", ResponseNamespace="urn:RAVi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response", IsNullable=true)]
        public string modifyPoiProVal([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="urn:pl.com.bcc.ws.classes")] PoiProValWrapper[] data) {
            object[] results = this.Invoke("modifyPoiProVal", new object[] {
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void modifyPoiProValAsync(PoiProValWrapper[] data) {
            this.modifyPoiProValAsync(data, null);
        }
        
        /// <remarks/>
        public void modifyPoiProValAsync(PoiProValWrapper[] data, object userState) {
            if ((this.modifyPoiProValOperationCompleted == null)) {
                this.modifyPoiProValOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodifyPoiProValOperationCompleted);
            }
            this.InvokeAsync("modifyPoiProVal", new object[] {
                        data}, this.modifyPoiProValOperationCompleted, userState);
        }
        
        private void OnmodifyPoiProValOperationCompleted(object arg) {
            if ((this.modifyPoiProValCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modifyPoiProValCompleted(this, new modifyPoiProValCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:RAVi", ResponseNamespace="urn:RAVi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response", IsNullable=true)]
        public string modifyPsPropVal([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="urn:pl.com.bcc.ws.classes")] PsPropValWrapper[] data) {
            object[] results = this.Invoke("modifyPsPropVal", new object[] {
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void modifyPsPropValAsync(PsPropValWrapper[] data) {
            this.modifyPsPropValAsync(data, null);
        }
        
        /// <remarks/>
        public void modifyPsPropValAsync(PsPropValWrapper[] data, object userState) {
            if ((this.modifyPsPropValOperationCompleted == null)) {
                this.modifyPsPropValOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodifyPsPropValOperationCompleted);
            }
            this.InvokeAsync("modifyPsPropVal", new object[] {
                        data}, this.modifyPsPropValOperationCompleted, userState);
        }
        
        private void OnmodifyPsPropValOperationCompleted(object arg) {
            if ((this.modifyPsPropValCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modifyPsPropValCompleted(this, new modifyPsPropValCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:RAVi", ResponseNamespace="urn:RAVi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response", IsNullable=true)]
        public string updateTextVar(int mandant, int processId, int propId, int tsId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string datetime, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string value) {
            object[] results = this.Invoke("updateTextVar", new object[] {
                        mandant,
                        processId,
                        propId,
                        tsId,
                        datetime,
                        value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateTextVarAsync(int mandant, int processId, int propId, int tsId, string datetime, string value) {
            this.updateTextVarAsync(mandant, processId, propId, tsId, datetime, value, null);
        }
        
        /// <remarks/>
        public void updateTextVarAsync(int mandant, int processId, int propId, int tsId, string datetime, string value, object userState) {
            if ((this.updateTextVarOperationCompleted == null)) {
                this.updateTextVarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateTextVarOperationCompleted);
            }
            this.InvokeAsync("updateTextVar", new object[] {
                        mandant,
                        processId,
                        propId,
                        tsId,
                        datetime,
                        value}, this.updateTextVarOperationCompleted, userState);
        }
        
        private void OnupdateTextVarOperationCompleted(object arg) {
            if ((this.updateTextVarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateTextVarCompleted(this, new updateTextVarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PoiProValWrapper))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pl.com.bcc.ws.classes")]
    public partial class PsPropValWrapper {
        
        private int mandantField;
        
        private int propNameIdField;
        
        private string[] propValField;
        
        private string psDateTimeField;
        
        private System.Nullable<int>[] sampleNumField;
        
        private int tsSetNameIdField;
        
        /// <remarks/>
        public int mandant {
            get {
                return this.mandantField;
            }
            set {
                this.mandantField = value;
            }
        }
        
        /// <remarks/>
        public int propNameId {
            get {
                return this.propNameIdField;
            }
            set {
                this.propNameIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("String", Namespace="urn:java/lang")]
        public string[] propVal {
            get {
                return this.propValField;
            }
            set {
                this.propValField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string psDateTime {
            get {
                return this.psDateTimeField;
            }
            set {
                this.psDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="urn:java/lang")]
        public System.Nullable<int>[] sampleNum {
            get {
                return this.sampleNumField;
            }
            set {
                this.sampleNumField = value;
            }
        }
        
        /// <remarks/>
        public int tsSetNameId {
            get {
                return this.tsSetNameIdField;
            }
            set {
                this.tsSetNameIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pl.com.bcc.ws.classes")]
    public partial class PoiProValWrapper : PsPropValWrapper {
        
        private bool disabledField;
        
        private int tsNameIdField;
        
        /// <remarks/>
        public bool disabled {
            get {
                return this.disabledField;
            }
            set {
                this.disabledField = value;
            }
        }
        
        /// <remarks/>
        public int tsNameId {
            get {
                return this.tsNameIdField;
            }
            set {
                this.tsNameIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void addPsPropValCompletedEventHandler(object sender, addPsPropValCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addPsPropValCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addPsPropValCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void addPoiProValCompletedEventHandler(object sender, addPoiProValCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addPoiProValCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addPoiProValCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void modifyPoiProValCompletedEventHandler(object sender, modifyPoiProValCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modifyPoiProValCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modifyPoiProValCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void modifyPsPropValCompletedEventHandler(object sender, modifyPsPropValCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modifyPsPropValCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modifyPsPropValCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void updateTextVarCompletedEventHandler(object sender, updateTextVarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateTextVarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateTextVarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591